version: "3.8"

services:
    db:
        image: mariadb:10.6
        container_name: galette-mariadb
        working_dir: /application
        volumes:
            - .:/application
            # - ./fixtures:/docker-entrypoint-initdb.d/
            - ./docker/mariadb:/etc/mysql/conf.d
        ports:
            - 3306:3306
        env_file:
            - ./.env.docker
        environment:
            - TZ=Europe/Paris
        networks:
            - default

    webserver:
        depends_on:
            - db
        image: nginx:alpine
        container_name: galette-webserver
        working_dir: /application
        volumes:
            - .:/application
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./docker/nginx/mime.types:/etc/nginx/mime.types
        environment:
            - TZ=Europe/Paris
        ports:
            - 8000:80
        networks:
            - default

    php-fpm:
        build: docker/php-fpm
        container_name: galette-php-fpm
        working_dir: /application
        environment:
            - TZ=Europe/Paris
        volumes:
            - .:/application
            - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini
            - ./docker/php-fpm/www-overrides.conf:/etc/php/7.4/fpm/pool.d/z-overrides.conf
            - ./docker/config.inc.php:/application/galette/config/config.inc.php

    phpmyadmin:
        depends_on:
            - db
        image: phpmyadmin/phpmyadmin:latest
        container_name: galette-phpmyadmin
        logging:
            driver: none
        environment:
            - PMA_HOST=db
            - PMA_USER=galette
            - PMA_PASSWORD=demo
        ports:
            - 8001:80
        volumes:
            - /sessions
        networks:
            - default
